

skills_list = [
    'kafka',
    'Python',
    'Java',
    'C++',
    'JavaScript',
    'SQL',
    'HTML',
    'CSS',
    'Git',
    'Linux',
    'Networking',
    'Cloud Computing',
    'Data Analysis',
    'Machine Learning',
    'Artificial Intelligence',
    'Cybersecurity',
    'Web Development',
    'Mobile App Development',
    'Database Management',
    'Agile Methodology',
    'DevOps',
    'UI/UX Design',
    'Big Data',
    'Data Science',
    'Blockchain',
    'Internet of Things (IoT)',
    'Virtual Reality (VR)',
    'Augmented Reality (AR)',
    'Robotics',
    'Natural Language Processing (NLP)',
    'Data Visualization',
    'Containerization',
    'Microservices',
    'Serverless Architecture',
    'Cloud Native Development',
    'API Development',
    'Test Automation',
    'Quality Assurance',
    'Project Management',
    'UI Testing',
    'UX Research',
    'Network Security',
    'Front-end Development',
    'Back-end Development',
    'Full Stack Development',
    'Responsive Web Design',
    'Mobile UI Design',
    'Data Warehousing',
    'ETL (Extract, Transform, Load)',
    'Data Mining',
    'Statistical Analysis',
    'Data Modeling',
    'Business Intelligence',
    'Enterprise Resource Planning (ERP)',
    'CRM (Customer Relationship Management)',
    'ERP Implementation',
    'Cloud Infrastructure',
    'Container Orchestration',
    'Server Administration',
    'Network Administration',
    'IT Support',
    'Troubleshooting',
    'System Integration',
    'IT Security',
    'Penetration Testing',
    'Risk Assessment',
    'Wireless Networking',
    'Network Monitoring',
    'Cloud Security',
    'Data Privacy',
    'Data Governance',
    'IT Governance',
    'ITIL (Information Technology Infrastructure Library)',
    'IT Service Management',
    'IT Operations',
    'IT Strategy',
    'IT Consulting',
    'Business Analysis',
    'Requirements Gathering',
    'Software Development Lifecycle (SDLC)',
    'User Acceptance Testing (UAT)',
    'Change Management',
    'IT Project Management',
    'IT Budgeting',
    'IT Vendor Management',
    'IT Auditing',
    'IT Compliance',
    'IT Risk Management',
    'IT Disaster Recovery',
    'IT Service Desk',
    'IT Documentation',
    'IT Training',
    'IT Recruitment',
    'IT Leadership',
    'IT Governance',
    'IT Architecture',
    'IT Asset Management',
    'IT Procurement',
    'IT Contracts',
    'IT Policies and Procedures',
    'IT Standards and Frameworks',
    'IT Performance Management',
    'IT Reporting',
    'IT Metrics and KPIs',
    'IT Stakeholder Management',
    'IT Communication',
    'IT Problem Solving',
    'IT Innovation',
    'IT Research and Development',
    'IT Ethics',
    'IT Sustainability',
    'IT Legal and Regulatory Compliance',
    'IT Business Continuity',
    'IT Disaster Response',
    'IT Incident Management',
    'IT Service Level Management',
    'IT Capacity Planning',
    'IT Asset Tracking',
    'IT Asset Disposal',
    'IT Asset Security',
    'IT Asset Inventory',
    'IT Asset Documentation',
    'IT Asset Auditing',
    'IT Asset Reporting',
    'IT Asset Lifecycle Management',
    'IT Asset Procurement',
    'IT Asset Contracts',
    'IT Asset Policies and Procedures',
    'IT Asset Standards and Frameworks',
    'IT Asset Performance Management',
    'IT Asset Metrics and KPIs',
    'IT Asset Stakeholder Management',
    'IT Asset Communication',
    'IT Asset Problem Solving',
    'IT Asset Innovation',
    'IT Asset Research and Development',
    'IT Asset Ethics',
    'IT Asset Sustainability',
    'IT Asset Legal and Regulatory Compliance',
    'IT Asset Business Continuity',
    'IT Asset Disaster Response',
    'IT Asset Incident Management',
    'IT Asset Service Level Management',
    'IT Asset Capacity Planning'
]
