FROM tiangolo/uvicorn-gunicorn:python3.11-slim

LABEL maintainer="Rahul Kumar <kr7168799@gmail.com>"

COPY requirements.txt /tmp/requirements.txt
RUN pip install --no-cache-dir -r /tmp/requirements.txt
COPY ./app /app
