name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master  # Set this to your default branch

jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
    - name: Check Out Repository
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and Push Docker Image
    #   uses: docker/build-push-action@v2
    #   with:
    #     push: true
    #     tags: villain1039532/gobackend:latest  # Change to your Docker Hub username and image name

    - name: Build and push Docker image
      run: |
          docker build -t villain1039532/mlcooker:latest ./docker-images/.
          docker push villain1039532/mlcooker:latest

  deploy:
    needs: build-and-push
    runs-on: self-hosted
    steps:
      - name: Stop and remove existing container
        run: docker stop mlcooker || true && docker rm mlcooker || true

      - name: Run Docker container
        run: docker run -d -p 3333:80 -e MAX_WORKERS="1"  --name mlcooker villain1039532/mlcooker:latest
  
  # deploy:
  #   needs: build-and-push
  #   runs-on: self-hosted
  #   steps:
  #   - name: Deploy to Server
  #     uses: appleboy/ssh-action@master
  #     with:
  #       host: ${{ secrets.SERVER_IP }}
  #       username: ${{ secrets.SERVER_USER }}
  #       key: ${{ secrets.SERVER_SSH_KEY }}
  #       script: |
  #         docker pull villain1039532/gobackend:latest  # Change to your Docker Hub username and image name
  #         docker stop gobackend || true  # Replace with your container name
  #         docker rm gobackend || true  # Replace with your container name
  #         docker run -d --name gobackend villain1039532/gobackend:latest  # Change to your Docker Hub username and image name and adjust settings as needed
